name: Project CI - linting, testing, building
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  ci_pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
        run: npm ci
      - name: build production
        run: npm run build:prod
        if: always()
      - name: lint ts
        run: npm run lint:ts
        if: always()
      - name: lint scss
        run: npm run lint:scss
        if: always()
      - name: test unit
        if: always()
        run: npm run test:unit
#      - name: build storybook
#        if: always()
#        run: npm run storybook:build
#      - name: test screenshots
#        run: npm run test:ui:ci
#        if: always()
